server:
  port: 8080
spring:
  application:
    name: cloud-consumer-order

  cloud:
    consul:
      host: 47.101.65.44
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true