server:
  port: 7001

eureka:
  instance:
    hostname: localhost #erreka服务端的实例名称
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检查索引服务
    fetch-registry: false
    service-url:
      # 设置与Eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/